GeneralDynamic.Web/GeneralDynamic.Web/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GeneralDynamic.Web.Models;
using Microsoft.AspNetCore.Authorization;

namespace GeneralDynamic.Web.Controllers
{
    [Authorize]
    public class PagesController : Controller
    {
        [Route("")]
        public IActionResult Dashboard()
        {
            return View();
        }
        [Route("Accounts")]
        public IActionResult Accounts()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }
        [Route("Signatures")]
        public IActionResult Signatures()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GeneralDynamic.Web/GeneralDynamic.Web/Views/Shared/_LoginLayout.cshtml
@using System

<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>GateKeeper - Login</title>

    <!-- Meta-Tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="robots" content="noindex">
    <link rel="shortcut icon" type="image/x-icon" href="~/favicon.ico" />
    <noscript> JavaScript is disabled in your browser. Please enable JavaScript to view the GateKeeper Server </noscript>
    <environment names="Development">

        <link href="~/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/css/material-dashboard.css" rel="stylesheet" />
        <link href="~/css/font-awesome.css" rel="stylesheet" />
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="~/css/site.css" rel="stylesheet" />

        <script src="~/js/jquery-3.2.1.min.js" type="text/javascript"></script>

    </environment>
    <environment names="Staging,Production">
        <link href="~/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/css/Site.css" rel="stylesheet" />


    </environment>


</head>

<body>

    <div class="wrapper wrapper-full-page">
        <div class="full-page login-page">



            <!--   you can change the color of the filter page using: data-color="blue | purple | green | orange | red | rose " -->
            <div class="content">

                <div class="container">



                    @RenderBody()




                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                <a asp-controller="Pages" asp-action="Dashboard">Dashboard</a>
                            </li>
                            <li>
                                <a href="https://www.gd.com/" target="_blank">Company</a>
                            </li>
                            <li>
                                <a href="mailto:support@gkchain.com"><p>Support</p> </a>
                            </li>
                        </ul>
                    </nav>
                    <p class="copyright pull-right">
                        © @DateTime.Now.Year  <a href="https://www.gd.com/" target="_blank">General Dynamics Corporation</a>
                    </p>
                </div>
            </footer>
        </div>
    </div>


    <environment names="Development">


        <!--   Core JS Files   -->

        <script src="~/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="~/js/material.min.js" type="text/javascript"></script>

        <!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->

        <script src="~/js/core.js"></script>
        <!-- Library for adding dinamically elements -->
        <script src="~/js/arrive.min.js" type="text/javascript"></script>
        <!-- Forms Validations Plugin -->
        <script src="~/js/jquery.validate.min.js"></script>
        <!--  Plugin for Date Time Picker and Full Calendar Plugin-->
        <script src="~/js/moment.min.js"></script>

        <!--  Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
        <script src="~/js/jquery.bootstrap-wizard.js"></script>
        <!--  Notifications Plugin, full documentation here: http://bootstrap-notify.remabledesigns.com/    -->
        <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
        <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
        <!-- Sliders Plugin, full documentation here: https://refreshless.com/nouislider/ -->
        <!--  Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
        <!--  DataTables.net Plugin, full documentation here: https://datatables.net/    -->
        <!-- Sweet Alert 2 plugin, full documentation here: https://limonte.github.io/sweetalert2/ -->
        <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
        <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
        <!-- Material Dashboard javascript methods -->
        <script src="~/js/material-dashboard.js?v=1.2.1"></script>
        <!-- Material Dashboard DEMO methods, don't include it in your project! -->
        @*<script src="~/js/demo.js"></script>*@





    </environment>
    <environment names="Staging,Production">


    </environment>

    @RenderSection("scripts", required: false)
</body>

</html>